# AWS SAM deploy configuration
# Run: sam deploy --guided  (first time)
# Run: sam deploy           (subsequent deploys)

version = 0.1

[default]
[default.global.parameters]
stack_name = "aiflow"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
profile = "aiflow"

[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "aiflow"
parameter_overrides = "SupabaseUrl=\"https://yzyjxwmnluboirzdpiwt.supabase.co\" FrontendOrigin=\"aiflow.d1et3kbekq7lb5.amplifyapp.com\""
image_repositories = []
disable_rollback = true
